version: '3'

services:
#  vue:
#    build:
#      context: .
#    volumes:
#      - vue_dist:/build
#    command: sh -c "rm -rf /build/* && cp -r /app/dist/* /build"

  express:
    build:
      context: ./express
    env_file:
      - .env
    volumes:
      - ./dist:/vue_dist:ro
    restart: unless-stopped

  nginx:
    build:
      context: ./nginx
    volumes:
      - ./arena:/arena
      - ./dist:/vue_dist:ro
    depends_on:
      - express
    env_file:
      - .env
    restart: unless-stopped

  nginx_ssl:
      image: rsdnlesc/docker-term-letsencrypt
      volumes:
        - ./cert:/cert
        - ./letsencrypt:/etc/letsencrypt
      env_file:
        - .env
      restart: unless-stopped
      ports:
        - 443:443
        - 80:80

volumes:
  vue_dist:
